# Copy this file to secrets.toml in the same folder (do NOT commit real keys)
# Streamlit Cloud: paste the contents of your final secrets.toml into the app's Secrets UI.

GROQ_API_KEY = "your_groq_api_key_here"
# Optional: choose a supported Groq model. Omit to use default.
GROQ_MODEL = "llama-3.1-8b-instant"
